In [7]:
import pandas as pd

def rating_class(row):
    if row <= 2:
        return 'low rate'
    elif row <= 4:
        return 'middle rate'
    elif row >= 4.5:
        return 'high rate'
    else: return 'unknown'

ratings = pd.read_csv('ratings.csv')
movies = pd.read_csv('movies.csv')
joined = ratings.merge(movies, on = 'movieId', how = 'left')
joined['class'] = joined['rating'].apply(rating_class)
joined.head(10)

,userId,movieId,rating,timestamp,title,genres,class
0,1,31,2.5,1260759144,Dangerous Minds (1995),Drama,middle rate
1,1,1029,3.0,1260759179,Dumbo (1941),Animation|Children|Drama|Musical,middle rate
2,1,1061,3.0,1260759182,Sleepers (1996),Thriller,middle rate
3,1,1129,2.0,1260759185,Escape from New York (1981),Action|Adventure|Sci-Fi|Thriller,low rate
4,1,1172,4.0,1260759205,Cinema Paradiso (Nuovo cinema Paradiso) (1989),Drama,middle rate
5,1,1263,2.0,1260759151,"Deer Hunter, The (1978)",Drama|War,low rate
6,1,1287,2.0,1260759187,Ben-Hur (1959),Action|Adventure|Drama,low rate
7,1,1293,2.0,1260759148,Gandhi (1982),Drama,low rate
8,1,1339,3.5,1260759125,Dracula (Bram Stoker's Dracula) (1992),Fantasy|Horror|Romance|Thriller,middle rate
9,1,1343,2.0,1260759131,Cape Fear (1991),Thriller,low rate

In [16]:
geo_data = {

'Центр': ['москва', 'тула', 'ярославль'],

'Северо-Запад': ['петербург', 'псков', 'мурманск'],

'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']
}

def geo_class(query):
    for k,v in geo_data.items():
        for v1 in v:
            if v1 in query.split(' '):
                return k
    return 'undefined'        
                        
queries = pd.read_csv('keywords.csv')
queries['region'] = queries['keyword'].apply(geo_class)
queries[queries['region'] != 'undefined'].head(10)

                       keyword   shows          region
127               авито москва  979292           Центр
370   авито ру санкт петербург  425134    Северо-Запад
849            авито ярославль  209581           Центр
1063       фарпост владивосток  176951  Дальний Восток
1236      банк санкт петербург  174375    Северо-Запад
1259                    москва  153050           Центр
1346           санкт петербург  144232    Северо-Запад
1396           гисметео москва  140279           Центр
1482          госуслуги москва  133061           Центр
1579                авито тула  126168           Центр